#######################################################################
# BASIC SETTINGS
#######################################################################
server:
  access-control: 0.0.0.0/0 refuse
  access-control: 127.0.0.0/8 allow
  access-control: ::0/0 refuse
  access-control: ::1 allow
  #access-control: 192.168.0.0/16 allow
  aggressive-nsec: yes
  auto-trust-anchor-file: "/etc/unbound/root.key"
  cache-max-ttl: 86400
  cache-min-ttl: 0
  deny-any: yes
  do-daemonize: no
  do-ip4: yes
  do-ip6: yes
  do-not-query-localhost: no
  do-tcp: yes
  do-udp: yes
  domain-insecure: "home"
  domain-insecure: "lan"
  edns-buffer-size: 1472
  harden-algo-downgrade: yes
  harden-below-nxdomain: yes
  harden-dnssec-stripped: yes
  harden-glue: yes
  harden-large-queries: yes
  harden-referral-path: yes
  harden-short-bufsize: yes
  hide-identity: yes
  hide-trustanchor: yes
  hide-version: yes
  incoming-num-tcp: 100
  identity: "DNS"
  infra-cache-numhosts: 100000
  infra-cache-slabs: 8
  interface: 0.0.0.0
  interface: ::0
  key-cache-slabs: 8
  log-queries: no
  minimal-responses: yes
  msg-cache-size: 256m
  msg-cache-slabs: 8
  neg-cache-size: 8m
  num-queries-per-thread: 8192
  num-threads: 8
  outgoing-range: 32768
  pidfile: "/etc/unbound/unbound.pid"
  port: 5353
  prefetch-key: yes
  prefetch: yes
  private-address: 10.0.0.0/8
  private-address: 172.16.0.0/12
  private-address: 192.168.0.0/16
  private-address: 169.254.0.0/16
  private-address: fd00::/8
  private-address: fe80::/10
  private-address: ::ffff:0:0/96
  qname-minimisation-strict: no
  qname-minimisation: yes
  ratelimit: 1000
  root-hints: "/etc/unbound/root.hints"
  rrset-cache-size: 512m
  rrset-cache-slabs: 8
  rrset-roundrobin: yes
  serve-expired: yes
  so-rcvbuf: 32m
  so-reuseport: yes
  so-sndbuf: 8m
  tls-cert-bundle: "/etc/ssl/certs/ca-certificates.crt"
  unwanted-reply-threshold: 10000
  use-caps-for-id: yes
  val-clean-additional: yes
  val-permissive-mode: yes
  verbosity: 1

#######################################################################
# REMOTE ZONE
#######################################################################
remote-control:
  control-enable: yes
  control-interface: 127.0.1.2
  control-port: 8953
  server-key-file: "/etc/unbound/unbound_server.key"
  server-cert-file: "/etc/unbound/unbound_server.pem"
  control-key-file: "/etc/unbound/unbound_control.key"
  control-cert-file: "/etc/unbound/unbound_control.pem"

#######################################################################
# FORWARD ZONE
#######################################################################
#forward-zone:
  #name: "."
  #forward-ssl-upstream: yes
  # Cloudflare
  #forward-addr: 1.1.1.1@853#cloudflare-dns.com
  #forward-addr: 1.0.0.1@853#cloudflare-dns.com
  #forward-addr: 2606:4700:4700::1111@853#cloudflare-dns.com
  #forward-addr: 2606:4700:4700::1001@853#cloudflare-dns.com
  # CleanBrowsing
  #forward-addr: 185.228.168.9@853#security-filter-dns.cleanbrowsing.org
  #forward-addr: 185.228.169.9@853#security-filter-dns.cleanbrowsing.org
  #forward-addr: 2a0d:2a00:1::2@853#security-filter-dns.cleanbrowsing.org
  #forward-addr: 2a0d:2a00:2::2@853#security-filter-dns.cleanbrowsing.org