#######################################################################
# BASIC SETTINGS
#######################################################################
server:
  access-control: 0.0.0.0/0 refuse
  access-control: 10.0.0.0/8 allow
  access-control: 127.0.0.0/8 allow
  access-control: 192.168.0.0/16 refuse
  access-control: ::0/0 refuse
  access-control: ::1 allow
  aggressive-nsec: "yes"
  auto-trust-anchor-file: "/etc/unbound/root.key"
  cache-max-ttl: 86400
  cache-min-ttl: 300
  chroot: "/etc/unbound"
  deny-any: "yes"
  directory: "/etc/unbound"
  do-daemonize: "no"
  do-ip4: "yes"
  do-ip6: "yes"
  do-not-query-localhost: "no"
  do-tcp: "yes"
  do-udp: "yes"
  domain-insecure: "home"
  edns-buffer-size: 1472
  harden-algo-downgrade: "yes"
  harden-below-nxdomain: "yes"
  harden-dnssec-stripped: "yes"
  harden-glue: "yes"
  harden-large-queries: "yes"
  harden-referral-path: "yes"
  harden-short-bufsize: "yes"
  hide-identity: "yes"
  hide-trustanchor: "yes"
  hide-version: "yes"
  identity: "DNS"
  incoming-num-tcp: 100
  infra-cache-numhosts: 100000
  infra-cache-slabs: 4
  interface: 0.0.0.0
  interface: ::0
  key-cache-size: 32m
  key-cache-slabs: 4
  minimal-responses: "yes"
  msg-cache-size: 64m
  msg-cache-slabs: 4
  neg-cache-size: 4m
  num-queries-per-thread: 4096
  num-threads: 4
  outgoing-range: 8192
  pidfile: "/etc/unbound/unbound.pid"
  port: 5353
  prefetch-key: "yes"
  prefetch: "yes"
  private-address: 10.0.0.0/8
  private-address: 169.254.0.0/16
  private-address: 169.254.0.0/16
  private-address: 172.16.0.0/12
  private-address: 192.168.0.0/16
  private-address: ::ffff:0:0/96
  private-address: fd00::/8
  private-address: fe80::/10
  qname-minimisation: "yes"
  ratelimit: 1000
  rrset-cache-size: 128m
  rrset-cache-slabs: 4
  rrset-roundrobin: "yes"
  serve-expired: "yes"
  so-rcvbuf: 8m
  so-reuseport: "yes"
  so-sndbuf: 8m
  tls-cert-bundle: "/etc/ssl/certs/ca-certificates.crt"
  use-caps-for-id: "yes"
  username: unbound
  val-clean-additional: "yes"
  verbosity: 0
# access-control: 127.0.0.1/32 allow
# access-control: 172.16.0.0/12 allow
# access-control: 192.168.0.0/16 allow
# prefer-ip6: "no"
# trust-anchor-file: root.key


###########################################################################
# FORWARD ZONE
###########################################################################
#forward-zone:
#  name: "."
#  forward-tls-upstream: "yes"

## Quad9
#  forward-addr: 9.9.9.9@853#dns.quad9.net
#  forward-addr: 149.112.112.112@853#dns.quad9.net
#  forward-addr: 2620:fe::fe@853#dns.quad9.net
#  forward-addr: 2620:fe::9@853#dns.quad9.net

## Cloudflare
#  forward-addr: 1.1.1.2@853#cloudflare-dns.com
#  forward-addr: 1.0.0.2@853#cloudflare-dns.com
#  forward-addr: 2606:4700:4700::1112@853#cloudflare-dns.com
#  forward-addr: 2606:4700:4700::1002@853#cloudflare-dns.com

###########################################################################
# REMOTE ZONE
###########################################################################
remote-control:
  control-enable: "yes"
  control-interface: 127.0.0.1
  control-port: 8953
  server-key-file: "/etc/unbound/unbound_server.key"
  server-cert-file: "/etc/unbound/unbound_server.pem"
  control-key-file: "/etc/unbound/unbound_control.key"
  control-cert-file: "/etc/unbound/unbound_control.pem"
